// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mkg20001/give-me-dns/lib"
)

// Injectors from wire.go:

func Init(config string) error {
	libConfig := lib.ProvideConfig(config)
	store := lib.ProvideStore(libConfig)
	error2 := lib.ProvideDNS(libConfig, store)
	return error2
}
